# Generated by Django 4.2.3 on 2023-07-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_contact_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
