# Generated by Django 4.2.4 on 2023-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_current',
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание текущей версии'),
        ),
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Признак текущей версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.SmallIntegerField(default=1, unique=True, verbose_name='Номер версии'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_is_active'),
        ),
    ]
