# Generated by Django 4.2.4 on 2023-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_version_only_one_active_version_is_possible_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='version',
            name='is_active_True',
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='is_active_True'),
        ),
    ]
