# Generated by Django 4.2.4 on 2023-08-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_version_is_active_true'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_active',
            new_name='is_active_version',
        ),
    ]
