# Generated by Django 4.2.4 on 2023-08-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'permissions': (('сan_change_description', 'can change description'), ('сan_change_category', 'can change category'), ('сan_change_is_published', 'can change is_published'), ('сan_view_price', 'can view price')), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
